image: Visual Studio 2015

before_build:
  - nuget restore

configuration:
  - Release

platform: Any CPU

build:
  project: OpenHardwareMonitor.sln
  verbosity: minimal

artifacts:
  - path: 'Bin\Release\'
