image: Visual Studio 2015

before_build:
  - nuget restore

configuration:
  - Release

platform: Any CPU

environment:
  matrix:
  - solution_name: OpenHardwareMonitor.sln
build:
  project: '%solution_name%'
  verbosity: minimal

artifacts:
  - path: 'Bin\Release\'
