name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.200'
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
  
      - name: Clean
        run: msbuild LibreHardwareMonitor.sln -t:Clean
    
      - name: Build
        run: msbuild LibreHardwareMonitor.sln -p:Configuration=Release
