name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1
      - uses: microsoft/setup-msbuild@v1.0.1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.200'          
  
      - name: Clean
        run: msbuild LibreHardwareMonitor.sln -t:Clean
        
      - name: NuGet restore
        run: nuget restore LibreHardwareMonitor.sln
    
      - name: Build
        run: msbuild LibreHardwareMonitor.sln -p:Configuration=Release
        
      - uses: actions/upload-artifact@v2
        with:
          name: executables
          path: |
            bin/Release/
